<!DOCTYPE html>
<html lang="en">
<head>
          <title>Test Pelican - Logging Errors</title>
        <meta charset="utf-8" />
        <meta name="generator" content="Pelican" />

        <meta name="Description" content="An event-driven networking engine written in Python and MIT licensed." />

        <link rel="stylesheet" type="text/css" href="https://judgegregg.github.io/pelitwi/theme/css/twistedtrac.css" />


</head>

<body>
        <div id="banner">
                <div id="top_grad"></div>
                <div id="tab">
                        <a href="https://twistedmatrix.com/trac/wiki">HOME</a>
                        <a href="https://twistedmatrix.com/trac/wiki/FrequentlyAskedQuestions">FAQ</a>
                        <a href="/">DOCS</a>
                        <a href="https://twistedmatrix.com/trac/wiki/Downloads">DOWNLOAD</a>
                </div>

                <div id="header">
                        <a id="logo" href="https://judgegregg.github.io/pelitwi/"><img src="https://judgegregg.github.io/pelitwi/theme/images/trac_banner.png" alt="Twisted" /></a>
                </div>
        </div>

<div id="mainnav" class="related">
	<ul>
		<li><a href="https://judgegregg.github.io/pelitwi">Twisted 21.2.0 documentation</a> Â»</li>
	</ul>
</div>
        <div id="ctxtnav" class="nav">
        </div>

    <section>

    <div class="document">
        <div class="documentwrapper">
        <div class="bodywrapper">
        <h1>Logging Errors</h1>
        
        <div class="entry-content">
        <p>The <a class="reference external" href="https://judgegregg.github.io/pelitwi/pages/interrupted-responses.html">previous example</a> created a server that
dealt with response errors by aborting response generation, potentially avoiding
pointless work. However, it did this silently for any error. In this example,
we'll modify the previous example so that it logs each failed response.</p>
<p>This example will use the Twisted API for logging errors. As was
mentioned in the <a class="reference external" href="https://judgegregg.github.io/pelitwi/pages/asynchronous-responses-via-deferred.html">first example covering Deferreds</a> , errbacks are passed an error. In the previous
example, the <tt class="docutils literal">_responseFailed</tt> errback accepted this error
as a parameter but ignored it. The only way this example will differ
is that this <tt class="docutils literal">_responseFailed</tt> will use that error
parameter to log a message.</p>
<p>This example will require all of the imports required by the previous example
plus one new import:</p>
<div class="highlight"><pre><span></span><span class="kn">from</span> <span class="nn">twisted.python.log</span> <span class="kn">import</span> <span class="n">err</span>
</pre></div>
<p>The only other part of the previous example which changes is
the <tt class="docutils literal">_responseFailed</tt> callback, which will now log the
error passed to it:</p>
<div class="highlight"><pre><span></span><span class="o">...</span>
    <span class="k">def</span> <span class="nf">_responseFailed</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">failure</span><span class="p">,</span> <span class="n">call</span><span class="p">):</span>
        <span class="n">call</span><span class="o">.</span><span class="n">cancel</span><span class="p">()</span>
        <span class="n">err</span><span class="p">(</span><span class="n">failure</span><span class="p">,</span> <span class="sa">b</span><span class="s2">&quot;Async response demo interrupted response&quot;</span><span class="p">)</span>
</pre></div>
<p>We're passing two arguments to <cite>err &lt;twisted.python.log.err&gt;</cite> here. The first is the error which is being
passed in to the callback. This is always an object of type <cite>Failure &lt;twisted.python.failure.Failure&gt;</cite> , a class which represents an
exception and (sometimes, but not always) a traceback. <tt class="docutils literal">err</tt> will
format this nicely for the log. The second argument is a descriptive string that
tells someone reading the log what the source of the error was.</p>
<p>Here's the full example with the two above modifications:</p>
<div class="highlight"><pre><span></span><span class="kn">from</span> <span class="nn">twisted.web.resource</span> <span class="kn">import</span> <span class="n">Resource</span>
<span class="kn">from</span> <span class="nn">twisted.web.server</span> <span class="kn">import</span> <span class="n">NOT_DONE_YET</span>
<span class="kn">from</span> <span class="nn">twisted.internet</span> <span class="kn">import</span> <span class="n">reactor</span>
<span class="kn">from</span> <span class="nn">twisted.python.log</span> <span class="kn">import</span> <span class="n">err</span>

<span class="k">class</span> <span class="nc">DelayedResource</span><span class="p">(</span><span class="n">Resource</span><span class="p">):</span>
    <span class="k">def</span> <span class="nf">_delayedRender</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">request</span><span class="p">):</span>
        <span class="n">request</span><span class="o">.</span><span class="n">write</span><span class="p">(</span><span class="sa">b</span><span class="s2">&quot;&lt;html&gt;&lt;body&gt;Sorry to keep you waiting.&lt;/body&gt;&lt;/html&gt;&quot;</span><span class="p">)</span>
        <span class="n">request</span><span class="o">.</span><span class="n">finish</span><span class="p">()</span>

    <span class="k">def</span> <span class="nf">_responseFailed</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">failure</span><span class="p">,</span> <span class="n">call</span><span class="p">):</span>
        <span class="n">call</span><span class="o">.</span><span class="n">cancel</span><span class="p">()</span>
        <span class="n">err</span><span class="p">(</span><span class="n">failure</span><span class="p">,</span> <span class="sa">b</span><span class="s2">&quot;Async response demo interrupted response&quot;</span><span class="p">)</span>

    <span class="k">def</span> <span class="nf">render_GET</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">request</span><span class="p">):</span>
        <span class="n">call</span> <span class="o">=</span> <span class="n">reactor</span><span class="o">.</span><span class="n">callLater</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">_delayedRender</span><span class="p">,</span> <span class="n">request</span><span class="p">)</span>
        <span class="n">request</span><span class="o">.</span><span class="n">notifyFinish</span><span class="p">()</span><span class="o">.</span><span class="n">addErrback</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">_responseFailed</span><span class="p">,</span> <span class="n">call</span><span class="p">)</span>
        <span class="k">return</span> <span class="n">NOT_DONE_YET</span>

<span class="n">resource</span> <span class="o">=</span> <span class="n">DelayedResource</span><span class="p">()</span>
</pre></div>
<p>Run this server as in the <a class="reference external" href="https://judgegregg.github.io/pelitwi/pages/interrupted-responses.html">previous example</a>
and interrupt a request. Unlike the previous example, where the server gave no
indication that this had happened, you'll see a message in the log output with
this version.</p>

        </div>
        </div>
        </div>
<div class="sphinxsidebar">
<div class="sphinxsidebarwrapper">
</div>
</div>    </div>

    </section>

        <div id="footer"><hr>
                <div> </div>
                <p class="left2">
        Copyright 2021, Twisted Matrix Labs. Ver 21.2.0. Built on 2021-02-28.<br />
        Site design<br />
        By <a href="http://huw.ugbox.net/">huw.wilkins.</a>

                </p>
                <p class="right"></p>
        </div>


</body>
</html>